'use strict';

const AUDIT_ACTIONS = Object.freeze({
  // Auth
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGOUT: 'USER_LOGOUT',
  USER_LOGIN_FAILED: 'USER_LOGIN_FAILED',
  USER_PASSWORD_RESET_REQUESTED: 'USER_PASSWORD_RESET_REQUESTED',
  USER_PASSWORD_RESET: 'USER_PASSWORD_RESET',
  USER_MFA_ENABLED: 'USER_MFA_ENABLED',
  USER_MFA_DISABLED: 'USER_MFA_DISABLED',

  // User management
  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',
  USER_DEACTIVATED: 'USER_DEACTIVATED',
  USER_REACTIVATED: 'USER_REACTIVATED',

  // Documents
  DOCUMENT_UPLOADED: 'DOCUMENT_UPLOADED',
  DOCUMENT_VIEWED: 'DOCUMENT_VIEWED',
  DOCUMENT_DOWNLOADED: 'DOCUMENT_DOWNLOADED',
  DOCUMENT_UPDATED: 'DOCUMENT_UPDATED',
  DOCUMENT_DELETED: 'DOCUMENT_DELETED',
  DOCUMENT_STATUS_CHANGED: 'DOCUMENT_STATUS_CHANGED',
  DOCUMENT_ASSIGNED: 'DOCUMENT_ASSIGNED',
  DOCUMENT_BARCODE_SET: 'DOCUMENT_BARCODE_SET',
  DOCUMENT_VERSION_CREATED: 'DOCUMENT_VERSION_CREATED',

  // Access control
  ACCESS_DENIED: 'ACCESS_DENIED',

  // Reports
  REPORT_EXPORTED: 'REPORT_EXPORTED',

  // Phase-based workflow
  DOCUMENT_PHASE_ADVANCED:  'DOCUMENT_PHASE_ADVANCED',
  DOCUMENT_PHASE_RETURNED:  'DOCUMENT_PHASE_RETURNED',
  DOCUMENT_PHASE_RESOLVED:  'DOCUMENT_PHASE_RESOLVED',
  WORKFLOW_CREATED:         'WORKFLOW_CREATED',
  WORKFLOW_UPDATED:         'WORKFLOW_UPDATED',
  WORKFLOW_DELETED:         'WORKFLOW_DELETED',

  // Admin
  DEPARTMENT_CREATED: 'DEPARTMENT_CREATED',
  DEPARTMENT_UPDATED: 'DEPARTMENT_UPDATED',
  DOCUMENT_TYPE_CREATED: 'DOCUMENT_TYPE_CREATED',
  DOCUMENT_TYPE_UPDATED: 'DOCUMENT_TYPE_UPDATED',
  DOCUMENT_TYPE_DEACTIVATED: 'DOCUMENT_TYPE_DEACTIVATED',
  ADMIN_USER_CREATED: 'ADMIN_USER_CREATED',
  ADMIN_USER_DEACTIVATED: 'ADMIN_USER_DEACTIVATED',
});

module.exports = { AUDIT_ACTIONS };
